#!/bin/bash
# software properties-common provides usefull scripts to handle PPA'S

#If executing without root execute commands bellow

echo "Return the number corresponding to what do you want to do\n"
echo "1 - Install ROS\n"
echo "2 - Install VNC server"
read option

if [[ option == 1 ]]
then 
    if [[ `id -u` != 0 ]] 
    then
        sudo apt update && sudo apt upgrade -y
        sudo apt install software-properties-common
        sudo add-apt-repository universe
        #refresh repository list and update packages
        #A GPG key here is used to ensure that we download from ROS2 repository and avoid downloading malicious code from someone pretendind to be ROS2 repository
        #Install curl to download the key and adds ROS2 key to the list of trusted keys
        sudo apt install -y curl
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        #refresh repository list and update packages
        sudo apt update && sudo apt upgrade
        #Install complete version of ROS2
        sudo apt install -y ros-foxy-desktop python3-argcomplete 
    #If I am root probably because I am in inside a docker container execute without sudo
    else
        apt update && apt upgrade -y
        apt install -y software-properties-common
        add-apt-repository universe
        apt install -y curl
        #apt install -y expect
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
        apt update && apt upgrade
        apt install -y ros-foxy-desktop python3-argcomplete
        #expect "Please select the geographic area in which you live *"
        #send -- "2\n"
        #expect "Please select the city or region corresponding to your time zone. *"
        #send -- "127\n"
    fi
    #source the environment everytime there is a new terminal
    echo "source opt/ros/foxy/setup.bash" > ~/.bashrc
if [[ option == 2 ]]
then
    echo "This is not implemented yet" 